name: Laravel Tests

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  laravel-tests:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_DATABASE: test_shule
          MYSQL_ROOT_PASSWORD: ${{ secrets.DB_ROOT_PASSWORD }}
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.0'

      - name: Copy .env
        run: php -r "file_exists('.env') || copy('.env.example', '.env');"

      - name: Wait for MySQL to be ready
        run: |
          timeout=300
          while ! mysqladmin ping --silent; do
              timeout=$(($timeout - 1))
              if [ $timeout -eq 0 ]; then
                  echo "Timeout waiting for MySQL to be ready"
                  exit 1
              fi
              sleep 1
          done

      - name: Create Database Schema
        run: php artisan migrate --force

      - name: Import Database Dump
        run: mysql -hlocalhost -uroot -p${{ secrets.DB_ROOT_PASSWORD }} test_shule < test_shule.sql

      - name: Install Dependencies
        run: composer install --no-scripts --no-interaction --prefer-dist

      - name: Generate Application Key
        run: php artisan key:generate

      - name: Run Tests
        run: vendor/bin/phpunit
